import { describe, test, expect } from 'vitest'
import {
  STUCK_AFTER_MS,
  selectJobsToKick,
  type BackstopJob,
} from './generation-backstop'

const NOW = Date.parse('2026-08-05T12:00:00.000Z')

function job(over: Partial<BackstopJob> = {}): BackstopJob {
  return {
    id: 'job-1',
    order_id: 'order-1',
    status: 'queued',
    started_at: null,
    ...over,
  }
}

function minutesAgo(n: number): string {
  return new Date(NOW - n * 60 * 1000).toISOString()
}

describe('selectJobsToKick — queued jobs are the whole point of the backstop', () => {
  test('kicks a queued job, because a queued job means the inline kick never landed', () => {
    const decisions = selectJobsToKick([job({ status: 'queued' })], NOW)
    expect(decisions).toHaveLength(1)
    expect(decisions[0].reason).toBe('queued')
  })

  test('kicks every queued job, not just the first', () => {
    const jobs = [
      job({ id: 'a', status: 'queued' }),
      job({ id: 'b', status: 'queued' }),
      job({ id: 'c', status: 'queued' }),
    ]
    expect(selectJobsToKick(jobs, NOW).map((d) => d.job.id)).toEqual(['a', 'b', 'c'])
  })

  test('a queued job is kicked regardless of how old it is — a paid order does not expire', () => {
    const ancient = job({ status: 'queued', started_at: minutesAgo(60 * 24 * 7) })
    expect(selectJobsToKick([ancient], NOW)).toHaveLength(1)
  })
})

describe('selectJobsToKick — running jobs are left alone until their worker must be dead', () => {
  test('leaves a freshly started job alone, so we never run two workers on one pack', () => {
    const fresh = job({ status: 'running', started_at: minutesAgo(1) })
    expect(selectJobsToKick([fresh], NOW)).toEqual([])
  })

  test('leaves a job alone just before the stuck threshold', () => {
    const nearly = job({ status: 'running', started_at: new Date(NOW - STUCK_AFTER_MS + 1000).toISOString() })
    expect(selectJobsToKick([nearly], NOW)).toEqual([])
  })

  test('kicks a job once it reaches the stuck threshold, because its worker outlived the 800s cap', () => {
    const stuck = job({ status: 'running', started_at: new Date(NOW - STUCK_AFTER_MS).toISOString() })
    const decisions = selectJobsToKick([stuck], NOW)
    expect(decisions).toHaveLength(1)
    expect(decisions[0].reason).toBe('stuck')
  })

  test('kicks a long-dead running job', () => {
    const dead = job({ status: 'running', started_at: minutesAgo(45) })
    expect(selectJobsToKick([dead], NOW)[0].reason).toBe('stuck')
  })

  test('treats a running job with no started_at as stuck rather than leaving it forever', () => {
    const unstamped = job({ status: 'running', started_at: null })
    expect(selectJobsToKick([unstamped], NOW)[0].reason).toBe('stuck')
  })

  test('treats an unparseable started_at as stuck rather than silently skipping it', () => {
    const garbage = job({ status: 'running', started_at: 'not-a-date' })
    expect(selectJobsToKick([garbage], NOW)[0].reason).toBe('stuck')
  })
})

describe('selectJobsToKick — finished work is never re-kicked', () => {
  test.each(['completed', 'failed', 'cancelled', ''])(
    'ignores a %s job, so a finished pack is never regenerated by the backstop',
    (status) => {
      expect(selectJobsToKick([job({ status })], NOW)).toEqual([])
    },
  )

  test('returns nothing for an empty queue', () => {
    expect(selectJobsToKick([], NOW)).toEqual([])
  })
})

describe('selectJobsToKick — mixed queue', () => {
  test('picks exactly the queued and stuck jobs out of a mixed batch', () => {
    const jobs = [
      job({ id: 'queued-1', status: 'queued' }),
      job({ id: 'running-fresh', status: 'running', started_at: minutesAgo(2) }),
      job({ id: 'running-stuck', status: 'running', started_at: minutesAgo(30) }),
      job({ id: 'done', status: 'completed', started_at: minutesAgo(30) }),
    ]
    expect(selectJobsToKick(jobs, NOW).map((d) => [d.job.id, d.reason])).toEqual([
      ['queued-1', 'queued'],
      ['running-stuck', 'stuck'],
    ])
  })

  test('honours an injected threshold so the rule can be tuned without editing the policy', () => {
    const running = job({ status: 'running', started_at: minutesAgo(5) })
    expect(selectJobsToKick([running], NOW, 10 * 60 * 1000)).toEqual([])
    expect(selectJobsToKick([running], NOW, 60 * 1000)).toHaveLength(1)
  })
})
