import styles from '../samples.module.css'

type DocumentControlProps = {
  documentTitle: string
  documentNumber: string
  companyName: string
  reviewer?: string
}

export function DocumentControl({
  documentTitle,
  documentNumber,
  companyName,
  reviewer = 'Olu Tayo, ReadyPack Compliance Reviewer',
}: DocumentControlProps) {
  return (
    <div>
      <div className={styles['doc-control-title']}>Document Control</div>
      <table className={styles['doc-control']}>
        <tbody>
          <tr>
            <td>Document Title</td>
            <td>
              {documentTitle} (Document {documentNumber})
            </td>
          </tr>
          <tr>
            <td>Prepared For</td>
            <td>{companyName}</td>
          </tr>
          <tr>
            <td>Document Owner</td>
            <td>Mark Whitfield, Founder</td>
          </tr>
          <tr>
            <td>Version</td>
            <td>1.0</td>
          </tr>
          <tr>
            <td>Issue Date</td>
            <td>7 June 2026</td>
          </tr>
          <tr>
            <td>Next Review Date</td>
            <td>7 June 2027 (or upon material change)</td>
          </tr>
          <tr>
            <td>Reviewed By</td>
            <td>{reviewer}</td>
          </tr>
          <tr>
            <td>Classification</td>
            <td>Confidential — Internal &amp; Customer Use</td>
          </tr>
        </tbody>
      </table>
      <p className={styles['doc-control-note']}>
        This document was generated by ReadyPack&apos;s compliance documentation platform
        and reviewed by an experienced compliance professional. It does not constitute
        legal advice.
      </p>
    </div>
  )
}
