// lib/documents/prompts/disclosure-snippets.ts
import type { DocumentType } from '@/types/database'
import {
  companyProfileBlock,
  formatAiTools,
  type PromptBuilder,
  type PromptIntake,
} from './types'

export const DOC_TYPE: DocumentType = 'customer_disclosure_snippets'

export const buildPrompt: PromptBuilder = (intake: PromptIntake) => {
  return `Generate the content_json for Customer Disclosure Snippets (ready-to-paste AI disclosures).

${companyProfileBlock(intake)}

AI TOOLS (relevant to user-facing disclosure):
${formatAiTools(intake.aiTools)}

OUTPUT SCHEMA (respond with ONLY this JSON object):
{
  "document_type": "customer_disclosure_snippets",
  "title": "Customer Disclosure Snippets",
  "prepared_for": "${intake.companyName}",
  "prepared_by": "ReadyPack Compliance Platform",
  "version": "1.0",
  "prepared_date": "${intake.preparedDate}",
  "review_date": "${intake.reviewDate}",
  "sections": [],
  "how_to_use_text": "A paragraph explaining that the snippets are ready-to-paste, tagged by context, and that bracketed placeholders should be replaced before use.",
  "snippet_index_table": {
    "table_id": "snippet-index",
    "columns": ["Tag", "Use case"],
    "rows": [
      ["WEBSITE FOOTER", "General disclosure on every public page"],
      ["SUPPORT HANDOVER", "When a human takes over from an AI assistant"],
      ["PROPOSAL DISCLOSURE", "Inside a client-facing proposal or SOW"],
      ["AUTO-RESPONDER", "Email auto-replies generated by AI"]
    ]
  },
  "public_snippets": [
    {
      "label": "Website footer · short form",
      "tag": "WEBSITE FOOTER",
      "body": "A 1-2 sentence disclosure for use in the website footer. Reference ${intake.companyName}'s AI Use Statement. Use bracketed [link] placeholder."
    },
    {
      "label": "In-product banner · chat widget",
      "tag": "SUPPORT HANDOVER",
      "body": "A 1-2 sentence banner for an AI chat widget, explaining a human will join if needed. Use [link] placeholder."
    },
    {
      "label": "Email auto-reply · out-of-hours",
      "tag": "AUTO-RESPONDER",
      "body": "A 1-2 sentence email auto-reply disclosing AI authorship, committing to a human follow-up timeframe."
    }
  ],
  "client_snippets": [
    {
      "label": "Proposal cover-page disclosure",
      "tag": "PROPOSAL DISCLOSURE",
      "body": "A 2-3 sentence cover-page disclosure for proposals, mentioning enterprise terms and human review."
    },
    {
      "label": "Statement of Work — AI use clause",
      "tag": "PROPOSAL DISCLOSURE",
      "body": "A 2-3 sentence SOW clause on AI use, no consumer-tool use of client confidential info, no training reuse."
    }
  ]
}

RULES:
- Each snippet body must be plain prose ready to paste — no markdown, no bullets.
- All snippets must reference ${intake.companyName} where appropriate.
- Output ONLY the JSON object.`
}
